### ISSUE TITLE
Add option for token->token attachment

### ISSUE THREAD

**Issue by canb227** [KayelGee/token-attacher#1]
If possible, a config option to allow token to token attachment would be wonderful. While this functionality is provided in part by mount Up!, the UI on this is much nicer. Plus MountUp! doesn't save attachment data between server restarts.

Thanks!

**Comment by KayelGee** [comment]
I'll leave this open as I might tackle this in the future. 
While this isn't a big feature itself the technical aspect is a little more complicated because as soon as this this is allowed I have to deal with circle references and moving attached elements of the complete hierarchy.

**Comment by SalieriC** [comment]
Since Mount Up! is not maintained any longer and not working for a while, this would be a great improvement. Frankly, the only one that would make me use this module as I don't really need any of the other features.

**Comment by KayelGee** [comment]
Enabled in 4.0
