### ISSUE TITLE
Unable to install 

### ISSUE THREAD

**Issue by Ornitorrincalado** [KayelGee/token-attacher#112]
Hi, good night. I'm trying to install this mod for foundry, the Token-Attacher, but when I try it, using the link in github ( https://raw.githubusercontent.com/KayelGee/token-attacher/master/module.json), foundry keeps telling me this:

![image](https://github.com/KayelGee/token-attacher/assets/132306015/60712afb-a111-467b-8e2e-9c95831ef1c5)

**Comment by gioppoluca** [comment]
the zip file in the module json does not exists, there is a zip in the release page under the tag section, but has a different address than the one in the module.json

**Comment by icristianhrimiuc** [comment]
I've also stumbled into this problem. I've ended up downloading the zip and manually extracting it to "%LocalAppData%\FoundryVTT\Data\modules". Everything seems to be working fine for now.

**Comment by KayelGee** [comment]
Fixed in the next release
