### ISSUE TITLE
Letting players attach their own tokens

### ISSUE THREAD

**Issue by karakune** [KayelGee/token-attacher#113]
In a 5e game I run, I have a player that owns a familiar that often moves at the same time as the character (because the familiar is on the character's shoulder). When I installed the module, I was expecting that they would have the UI to attach the familiar's token to the character's token, but it seems the UI is GM only. Would it be possible to make the UI available to players, for use with tokens they own?

Thank you in advance

**Comment by KayelGee** [comment]
Either take a look at the mount up macro or the mount up module.

karakune ***@***.***> schrieb am Fr., 5. Apr. 2024, 02:39:
