### ISSUE TITLE
V12 Support?

### ISSUE THREAD

**Issue by Deladriendil** [KayelGee/token-attacher#118]
currently unable to install in V12, will this get V12 support?

**Comment by KayelGee** [comment]
yes in fact I'll upload the current version today so people can test it.

**Comment by KayelGee** [comment]
It was stupid of me to close this. I'll reopen for visiblity.
I've added a pre-release for V12 for anyone that wants to test the new version. A lot of code changed so I appreciate any bug reports.

**Comment by Neaferu** [comment]
I often suffer from the dreaded ID 10 T error, but I can't seem to get the latest version to install.  I believe I have followed the processes correctly but I might have missed something.  Or is this still in beta and not fully released to everyone yet?

**Comment by DMSavian** [comment]
> I often suffer from the dreaded ID 10 T error, but I can't seem to get the latest version to install. I believe I have followed the processes correctly but I might have missed something. Or is this still in beta and not fully released to everyone yet?

Same here. Every time I have tried, it says I am trying to install the older version.

**Comment by KayelGee** [comment]
I've made an official release now, do you still have issues with that?

**Comment by DMSavian** [comment]
The official worked for me! Thank you for responding so quickly. <3

**Comment by Neaferu** [comment]
> I often suffer from the dreaded ID 10 T error, but I can't seem to get the latest version to install. I believe I have followed the processes correctly but I might have missed something. Or is this still in beta and not fully released to everyone yet?

working just fine!
