### ISSUE TITLE
Cannot attach sound or light in 0.7.8

### ISSUE THREAD

**Issue by caerandir** [KayelGee/token-attacher#12]
Hi, just tried the module, and it's great, just what I need! In your mini-tutorial you show that you can attach an ambient light by selecting it via the rectangle tool and then attach it. my problem: The rectangle tool seems no longer be there (using Foundry 0.7.8) - deactivated all modules to double check it's not a module that kills it - but no rectangle tool in vanilla either... Help appreciated!

**Comment by KayelGee** [comment]
> To be able to attach measure templates, lights, sounds and journals you need the select-tool-everywhere module, as of writing this there is no select tool in those controls.

It's the second sentence in the description. You can also attach via macro if that's more your thing.

**Comment by caerandir** [comment]
Ouch, stupid me. Sorry for that!
