### ISSUE TITLE
Not working in PF2e

### ISSUE THREAD

**Issue by RPGArchivist** [KayelGee/token-attacher#123]
Getting this error in Foundry v12 and PF2e system. Works just fine in DnD5e.
![image](https://github.com/user-attachments/assets/1ca5ca37-a886-434d-b651-33cba7f20a0a)

**Comment by KayelGee** [comment]
Fixed in the newest version

**Comment by RPGArchivist** [comment]
Doesn't seem to work. The same is happening in other minor systems such as Tormenta20.
![image](https://github.com/user-attachments/assets/4d3fe7d7-76f5-41c0-9c1c-6a7fb3b19465)

**Comment by KayelGee** [comment]
I'm stupid. I tested the wrong thing.
I've pushed a new update which should fix the issue, this time for real.

**Comment by RPGArchivist** [comment]
It works. Thanks, you are the best.
