### ISSUE TITLE
Constant errors with PF2 system

### ISSUE THREAD

**Issue by Nerull91** [KayelGee/token-attacher#13]
Hello,

Every time I add or remove a condition, I get the following errors:
![image](https://user-images.githubusercontent.com/29990125/101370695-d0c88d00-3877-11eb-9367-4754745222b9.png)

Confirmed with no other modules loaded and I am using foundry 0.7.8.

Thanks!

**Comment by KayelGee** [comment]
Fixed in 3.1.2
