### ISSUE TITLE
Macro methods no longer seem to exist 

### ISSUE THREAD

**Issue by Lazytron** [KayelGee/token-attacher#16]
FVTT .7.9
dnd5e 1.2
TA 3.2.1
hosted on Forge

All methods designed for macros cannot be called suddenly (UI elements seem to work):
![image](https://user-images.githubusercontent.com/32400728/103250401-4258a000-4939-11eb-9d1f-b1c95b38e0a3.png)

**Comment by KayelGee** [comment]
Works for me. Do you have any other errors in the console?

**Comment by Lazytron** [comment]
That was pretty much it, similar for all of the other methods. 

Started working again inexplicably, maybe it was a world or forge issue somewhere.

**Comment by KayelGee** [comment]
Just fyi this is a issue in the current release. It is caused by a scene change. There'll be a fix for it tomorrow.
