### ISSUE TITLE
Cannot select individual tokens in a squad for combat attacks

### ISSUE THREAD

**Issue by caewok** [KayelGee/token-attacher#18]
This is either a feature request or a bug. And I understand if it is simply not achievable. 

The scenario is that I have a "squad" of tokens, where a group are following a leader. I would like to be able to select each token in the squad in order to initiate combat for that token. (For example, to have that token use a weapon in the macro bar, I need to select the token, then select the weapon macro to attack a target.) But because the tokens are following the leader, I am only able to select the leader. The only way I see to select an individual token to use for combat is to first remove the token from the group. Further, I am unable to open the character sheet corresponding to any given follower token. 

This is, of course, less than desirable if one has a lot of squads in a major battle scene. The moving around by squads is great, but having to de-construct the squad and re-construct it each round of combat is less than ideal. But maybe I am missing a simple way to achieve this!

Again, I understand if this is simply beyond what the module can achieve. But if it is possible, it would be a great improvement!

(Incidentally, the same is not true of say, lights attached to a group. I can attach a light and then, while it is part of the group, right-click to toggle the light on and off, and double-click to open the light settings panel.)

**Comment by KayelGee** [comment]
See the readme `Enable selection of an attached element by selecting the element and then pressing the unlock button. To prevent the selection again use the lock button.`. If you can't get it to work you can get in touch over discord.

**Comment by caewok** [comment]
Thanks!
