### ISSUE TITLE
Token with wall attached sometimes throw permission error when DM deletes them

### ISSUE THREAD

**Issue by Theik** [KayelGee/token-attacher#19]
How to reproduce:

Make a token, attach a tile and some walls to it.
Save these token settings as a new actor so you can drag new ones on the map.
Drag some copies of it onto the map.
Now as the DM, delete the tokens.

Every now and then the system seems to bug out and the player screen will show:
Error: User [Player name] lacks permission to delete Walls in parent aC6KsUiJuwnkA8ma

This will also result in the attached tile not getting deleted, resulting in a desync where the player will continue seeing the tile, while it is already gone on the DMs screen
![image](https://user-images.githubusercontent.com/6170572/108263481-a09a4600-7166-11eb-9d6b-b7b11439945e.png)

**Comment by KayelGee** [comment]
Should be fixed in 4.0.2
