### ISSUE TITLE
Add setting/flag to disable movement animation for attached tokens

### ISSUE THREAD

**Issue by jessev14** [KayelGee/token-attacher#21]
Tiles (and other non-token entities) don't have movement animations, so moving a parent token attached to tiles and tokens can result in a weird effect where the tiles pop into place immediately, but the tokens still take time to animate to the new position. This can be slightly jarring when moving large distances.

https://user-images.githubusercontent.com/68755874/108533578-22918880-72a7-11eb-9e32-b5e10ef040ae.mp4

I think the most straightforward way to address this would be to conditionally add `{animate: false}` to the attached elements update for tokens. (e.g. `token.update({x: newX, y: newY }, {animate: false})`). A possible alternative may be to disable the animation through the `preUpdateToken` hook, though I'm less familiar with that approach.

The condition could be set the way locked/unlocked status is set through the token attacher UI (or if that would clutter up the UI too much, I think allowing it to be set manually through the console/a macro would be sufficient since it might be a niche use case).

(enso#0361)

**Comment by KayelGee** [comment]
I've already thought about that aswell but I didn't dive into the code necessary for it.
I think it will end up being both an macro and a ui button.

**Comment by KayelGee** [comment]
This'll be added in the next update
