### ISSUE TITLE
Issue with attaching multiple lights

### ISSUE THREAD

**Issue by Flintwyrm** [KayelGee/token-attacher#23]
When I attach multiple lights to a token on my end they attach and move with the token and tiles attached. but on the player side only one light moves with the rest of the things attached. they are using chrome. and I run from my computer using the Foundry client.

**Comment by KayelGee** [comment]
This is actually a core foundry bug. 
When you look at the console of the player you'll notice an error there. This error also happens with no modules when the GM moves a light. This error prevents the lights on the clients to update correctly as the first light will throw the error and prevent the other ones to update.
I've reported the issue.

**Comment by aprusik** [comment]
Do you happen to know if there is a "quick fix" for this in the meantime? Since Foundry probably wont receive a stable public update for quite some time with all the work being dedicated to 0.8...

**Comment by KayelGee** [comment]
I didn't see how I could add a work around so I would say there's no quick fix as one would probably need to change foundry.js in some form.
