### ISSUE TITLE
Moving a vehicle with attached tokens, put those tokens behind the vehicle

### ISSUE THREAD

**Issue by Merudo** [KayelGee/token-attacher#25]
If a vehicle (say, a boat or mounted animal) is moved, all the attached token are moved with it, but the z axis is not respected. The attached tokens all end up "behind" the vehicle, and cannot be seen or interacted with.

This also occurs if the "Mount Up" macro is used.

Example: the elf token should be clearly displayed on the dinosaur's back, but instead is largely hidden behind the animal:

![image](https://user-images.githubusercontent.com/7371085/113641167-b1cde200-9642-11eb-9b58-8c8b7f6f2a45.png)

If the elf was instead attached say to the deck of a ship, moving the ship would fully hide the elf behind the ship.

**Comment by KayelGee** [comment]
It's how foundry handles token z ordering, the selected token will always be on top.
I recommend to make a transparent token image as the actual mount and attach a tile with the mounts image to that token. Tiles will always be under tokens and that way your tokens will be on top.

**Comment by Merudo** [comment]
The transparent token idea is okay and will allow us to see both mount and rider, however it will still be hard to select the rider if the transparent token is in the foreground.

**Comment by KayelGee** [comment]
I've faced the same issue and have no good solution to that sadly.
If only one person is riding then you can attach the mount to the player instead. If you leave out the `tokenAttacher.setElementsLockStatus` line in the Mount Up macro the attached elements won't be selectable. 
This has it's own drawbacks.
