### ISSUE TITLE
Macro pack name is "example-macros"

### ISSUE THREAD

**Issue by dmrickey** [KayelGee/token-attacher#28]
The UX* for this is so bad it's basically a bug. "Example Macros" is a super generic name so if I (or anyone) has a bunch of mods installed, it's not clear that this specific compendium belongs to Token Attacher. Simply renaming it something like "Token Attacher Macros" or "TA Macros" would help (though I personally would prefer the full name).

*UX means user experience

**Comment by KayelGee** [comment]
Well but it is clear that it belongs to token attacher as with every compendium that comes from a module the module name is right under the name of the compendium.
```
Example Macros
Macro (token-attacher)
```

**Comment by dmrickey** [comment]
I understand you're _attached_ to your current name, but I've seen multiple asks about where the included macros are located. I understand the module name is visible by default, but not in all circumstance (a very common circumstance is if using Compendium Folders). I understand I'm being very abrupt/blunt, but I don't see harm in changing the pack name so that it's useful in _all_ circumstances rather than its limited view right now

**Comment by KayelGee** [comment]
Don't get me wrong I am open to changing the name I just don't see the issues you're trying to point out.

`I've seen multiple asks about where the included macros are located` 
This is more of a problem with the readme not being clear enough or people not reading it(which happens).

I'm using compendium folders and they are not hiding anything. Is there an option to disable the module name somewhere?
Can you show me a screenshot where it's missing? You can also hit me up on discord I usually answer quicker there.

**Comment by IrmatDen** [comment]
Hello,
I'm sorry to necro this ticket, but I would like to add a point to why a more specific name would help. It is true that the mod name is displayed under the compendium, but you can't search for it (at least in v9).

Picture searching for "exa" (as in example macros):
![image](https://user-images.githubusercontent.com/4919540/186544390-adf7fba8-604b-4fbf-89fb-378035958ea6.png)

Picture searching for tok (or even token-attacher etc...):
![image](https://user-images.githubusercontent.com/4919540/186544473-45b9ef13-e4c7-4e19-84b9-5104a8d0b02d.png)

I have a lot of compendiums, so I was about to manually copy past the db, but then I thought about checking if and how the compendium pack was registered. That's when I realised the public name of the pack couldn't be found with how I was looking for it.

Whatever your final decision is on this topic, thanks for the work you put in :)
