### ISSUE TITLE
errors loading world with latest version of libWrapper

### ISSUE THREAD

**Issue by Tupsi** [KayelGee/token-attacher#29]
I am getting lots of these since a few days, supposingly since that dreaded libWrapper update. Makes my world unplayable until I disable token-attacher (and depended modules with it). 

![image](https://user-images.githubusercontent.com/3730499/114826501-de62c600-9dc7-11eb-9513-aeec7c038377.png)

using latest versions atm (update all modules) from this morning.

I moved back to an old version of libWrapper (1.3.6) and now the installation is usable again, although still getting some errors.

![image](https://user-images.githubusercontent.com/3730499/114837009-85009400-9dd3-11eb-9a47-1bcf5e390314.png)

**Comment by Tupsi** [comment]
the 2nd error seems dependend on the module compendiumfolders. I don't get that one, if I disable it.

**Comment by dmrickey** [comment]
I'm also seeing the second error when logging in as a player

**Comment by KayelGee** [comment]
I guess this has resolved itself
