### ISSUE TITLE
Template Error

### ISSUE THREAD

**Issue by Khybersghost** [KayelGee/token-attacher#31]
Having an issue where an attached template immediately reverts back to its original size once the token is moved. For specifics, the issue occurs after resizing a template that is already attached to a token. So, if I create a 10ft circle and attach it to a character token, I can move it around just fine. If I later resize that template to 15 ft (for example), it works fine until the token is moved at which point it immediately reverts to the original size at the time of attachment. I've disabled all of my mods except those listed below. I am not getting any errors in the console. Not sure if this is a feature (locking the template size) that was recently introduced or a bug. 

Foundry 0.7.9
PF2e Ruleset
Token Attacher
Libwrapper
Select Anything Tool (required to attach the template)

**Comment by KayelGee** [comment]
Once something is attached it'll keep their position and size relative to the base token. If you want to change the size of the template but keep the token the same size you can use the quick edit mode. This behaviour was introduced in token attacher 4.0.

**Comment by Khybersghost** [comment]
Ok, I thought it may have been something I missed. Thanks
