### ISSUE TITLE
Please don't force activate scenes

### ISSUE THREAD

**Issue by mkahvi** [KayelGee/token-attacher#32]
Repeating what I mentioned in Discord: please remove the forced scene activation.

It was very surprising and extremely undesirable to have _all_ scenes activate and thus load up in sequence, including ones players aren't supposed to know about yet.

If the mass scene migration is desired to happen anyway, all the info should be accessible without using canvas or accessing them via the active scene handle, since you aren't doing rendering related updates (or at least shouldn't, since it doesn't matter for scenes that aren't currently active).

**Comment by KayelGee** [comment]
In the next update this migration process won't be called on new worlds anymore(as that was unnecessary), which should mostly resolve the issue, as most user probably started using token attacher with version 4.0.
