### ISSUE TITLE
Not resizing prefabs for different grid sizes

### ISSUE THREAD

**Issue by BiraN2019** [KayelGee/token-attacher#33]
Made a simple prototype token with an actor and a drawing. Looks fine on one scene with a 70px grid, but the next scene it doesn't scale correctly. The drawing stays at the width of the previous scene, while the actor resizes to the new grid size (128px). Could this be the result of the drawing not being snapped to a grid in the prefab? Using tiles scales fine, it is only when using a drawing that it fails to scale.
![1](https://user-images.githubusercontent.com/55107659/118403427-2709db00-b623-11eb-8ce9-d19d3cd69d32.JPG)
![2](https://user-images.githubusercontent.com/55107659/118403428-27a27180-b623-11eb-80b4-dced4e39220b.JPG)

**Comment by KayelGee** [comment]
Drawings weren't scaled right. This'll be fixed in the next update.
