### ISSUE TITLE
Compatibility with 0.8.x

### ISSUE THREAD

**Issue by rmasoni** [KayelGee/token-attacher#34]
Currently on 0.8.5 the module doesn't work. Nothing gets attached.

**Comment by KayelGee** [comment]
I should've opened the issue myself for visibility.
There's a few issues with 0.8.x, but I'm working on it.
I'm not sure if I'll be able to hit the end of may target for 0.8.x stable.

**Comment by karpana** [comment]
Had a chance to play with the update. Thank you.  

I can now attach tiles to tokens in 0.8.6.
