### ISSUE TITLE
Question: tile context menu when attached to token not accessible. 

### ISSUE THREAD

**Issue by karpana** [KayelGee/token-attacher#36]
Hi there. 
Thank you for the compatibility update for 0.8.x

I'm a new user of token attacher , and I can't figure out how access the right-click context menu of a tile, when it is attached to a token, such that I can hide the tile from players. 

Is this expected behaviour?

**Comment by KayelGee** [comment]
that's expected behaviour. See the readme "Attached elements can no longer be selected via the rectangle selection tool of each layer, unless the attach ui of the base token is open or you use the unlock feature. "
