### ISSUE TITLE
Error when moving token while quick edit is enabled

### ISSUE THREAD

**Issue by watermelonwolverine** [KayelGee/token-attacher#37]
token-attacher.js:2191 Uncaught (in promise) ReferenceError: _id is not defined
    at token-attacher.js:2191
    at Array.map (<anonymous>)
    at saveAllQuickEditOffsets (token-attacher.js:2190)

Steps to reproduce:
- Select token with stuff attached (in my case two tiles)
- Activate Quick edit
- Move selected token

After that a new error is logged in my console

**Comment by KayelGee** [comment]
Thanks for the report. This will be fixed in the next patch.
