### ISSUE TITLE
unable to select token with 4.1.0

### ISSUE THREAD

**Issue by wmve** [KayelGee/token-attacher#38]
versions:
![image](https://user-images.githubusercontent.com/55966777/121980398-dd173080-cd59-11eb-9c86-44a5306b8aab.png)

i've been waiting for more stability from Token Attacher with D35E and latest update shows a new behaviour with an existing token in my world.  

1. load world
2. select token in question
**expected behaviour:** able to select token (see yellow outline)
**actual behaviour:** unable to select token

- i don't find any other tokens on the map that behave this way
- this happens in a player session or the gamemaster server console
- turning off Token Attacher fixes this behaviour

i watched the console and only see one strange info message, but it only when i successfully move OTHER tokens.  not sure if it means anything.  i'll let Rughalt (D35E) know as well.
![image](https://user-images.githubusercontent.com/55966777/121980364-cf61ab00-cd59-11eb-8c30-81c2db15376c.png)

**Comment by wmve** [comment]
sorry, forgot to add export of actor:

[fvtt-Actor-meranis.210614.zip](https://github.com/KayelGee/token-attacher/files/6652440/fvtt-Actor-meranis.210614.zip)

**Comment by KayelGee** [comment]
so I checked your actor export and I don't see any token attacher related data in there. Are you sure this is the correct actor?

When you attach a token to another token then by default you're unable to select the token anymore unless you unlock the token in the attach ui. You also are able to select the token if you have the attach ui of the parent open or if you enable quick edit mode.
If you accidently deleted the parent token while you had token attacher disabled you can clear the flags of the token via macro like this `token.update({['flags.-=token-attacher']:null})`

**Comment by wmve** [comment]
yup, pretty sure that was the right one.  i have deleted the token from the map (which i could only do with the module disabled), and dragged the actor to the map again.  the new token does not exhibit this behaviour.  don't know what to suggest if i can't reproduce anymore.  close but keep an eye out i guess?

**Comment by KayelGee** [comment]
I think what happend was that you had the token attached to some parent token and while the module was disabled you deleted that parent. Because the module was disabled the data on the child didn't change so it still thought it was attached to something.
