### ISSUE TITLE
Compatibility with Multilevel Tokens

### ISSUE THREAD

**Issue by DarKDinDoN** [KayelGee/token-attacher#4]
Hello,

Thx for this great module.
Do you think it's possible to make it compatible with Multilevel Tokens so it doesn't crash on init?
https://github.com/grandseiken/foundryvtt-multilevel-tokens

![image](https://user-images.githubusercontent.com/1687854/94362859-6b5d6080-00be-11eb-960e-637a0b6a36ad.png)

Thx

**Comment by KayelGee** [comment]
I'll have to look at it, but it looks like I can fix that

**Comment by KayelGee** [comment]
Can you check if this error still shows up with the current version? I had trouble reproducing it.

**Comment by DarKDinDoN** [comment]
Yep, we good 👍
