### ISSUE TITLE
GM Menu Button Inaccurate

### ISSUE THREAD

**Issue by tjlanza** [KayelGee/token-attacher#44]
Foundry 0.8.7, TA 4.1.2

The button is labeled "Force migration of current Scene", but it acts on the _active_ scene, not the _current_ scene.

As shown below, the first scene is the active scene, but the second is the current/visible scene.

![image](https://user-images.githubusercontent.com/21128724/123139005-b759ed80-d423-11eb-9781-fb90924a030e.png)

**Comment by KayelGee** [comment]
I didn't even know that the active scene isn't the current viewed scene. I'll reword that in the next update

**Comment by KayelGee** [comment]
Changed in next update.
