### ISSUE TITLE
Unexpected behavior when copying and pasting the token

### ISSUE THREAD

**Issue by danielrab** [KayelGee/token-attacher#5]
actions:
1) attach anything to a token
2) copy the token by pressing Ctrl + c
3) paste it by pressing Ctrl + v
4) move the new token

actual behavior: the attached objects move.

expected behavior, option 1 (easier to implement): nothing happens, only the original token is controlling the objects.

expected behavior, option 2 (more useful): the attached objects are copied with the new token and the copy is controlled by the new token, instead of the original.

**Comment by KayelGee** [comment]
Option 2 is what I'm aiming for in the future. Same thing with deleting the token, then the attached objects should be removed aswell.

**Comment by KayelGee** [comment]
This will be fixed in version 3.1+
