### ISSUE TITLE
Two minor issues related to UI

### ISSUE THREAD

**Issue by paulohdsc** [KayelGee/token-attacher#57]
1. There is an unused area under the token image in the control tools (which I marked in red below) that prevents interaction with canvas elements.

![ss](https://user-images.githubusercontent.com/75817094/134972999-50a6bb87-668c-4e4a-9aee-904a08fb64d1.jpg)

2. Unlike with the other tools, the module does not show a tooltip for the users when hovering the mouse cursor over lock and unlock tools.

![chrome_P36o8Vrz0f](https://user-images.githubusercontent.com/75817094/134975362-9286ab32-8edf-4722-8593-51d3deb7f924.jpg)

**Comment by KayelGee** [comment]
Fixed in next update
