### ISSUE TITLE
Import Packs Feature Not Working in FoundryVTT v0.9.x

### ISSUE THREAD

**Issue by Zephyr2011** [KayelGee/token-attacher#63]
The Import Packs feature and scripts do not appear to be working in FoundryVTT v0.9.x Tested using compendiums compiled in a DnD 5e world and imported on DSA5 and PF1e worlds. In both cases the actors compendiums do not import. A force re-import yields an empty folder.

Happy to provide additional information to help troubleshoot this.

**Comment by KayelGee** [comment]
that was fixed in 4.3.0
