### ISSUE TITLE
Mount Up! macro not working

### ISSUE THREAD

**Issue by samursus** [KayelGee/token-attacher#64]
As in the title... nothing seems to happen when I click that macro, whereas the others work with the appropriate chat bubbles

**Comment by KayelGee** [comment]
Oh yeah the `token.update` doesn't work anymore.
It should be `await canvas.scene.updateEmbeddedDocuments('Token',[{_id:token.document.data._id, x: newCoords.x, y: newCoords.y}]);`.

**Comment by KayelGee** [comment]
it can be replaced with `token.document.update` and `token.id`

**Comment by KayelGee** [comment]
Fixed in next update
