### ISSUE TITLE
[Feature Request] Allow the rider token to be moved as long as it does not leave the area of mount token

### ISSUE THREAD

**Issue by p4535992** [KayelGee/token-attacher#67]
Hi, I have developed a small utility module which is based on your module [Mountup](https://github.com/p4535992/MountUp/blob/master/src/module/tokenAttacherHelper.ts). In particular as regards the up and drop macros in a token.

I'm banging my head on a problem that I can't solve and I was thinking about analyzing your code to find out if it was possible to add (if it doesn't already exist and I missed it) the possibility that when you link a `token A` to a `token B`, not to constrain the coordinates of `token A`, but to allow it to be moved as long as it does not leave the area of `token B`.

To make it clear what is the result I want, I'll give you two gifs the first is the current result the second what I would like, that is to be able to move the rider inside the mount.

What i have now.
![img1](https://i.imgur.com/HWvbxlg.gif)
What i want
![img2](https://i.imgur.com/WcOP2kJ.gif)

I don't know if it will be useful to you this is the function I use to check if the token is contained within the area of another token.

```
function riderIsContainedOnMount(riderToken, mountToken) {
  let x = riderToken.x;
  let y = riderToken.y;
  let width = riderToken.w;
  let height = riderToken.h;
  return Number.between(mountToken.x, x, x + width) && Number.between(mountToken.y, y, y + height);
 }
```

**Comment by KayelGee** [comment]
You could do it in a kinda roundabout way by detaching the token and then reattaching it at the new location. 
Although on second thought it's not that easy.
You'd need to set options which would prevent TA from blocking the movement, which would only be possilbe if you'd monkey patch the ui drop function.
Let me think about it some more.

**Comment by KayelGee** [comment]
Next update will allow setting a "canMoveConstrained" flag via api. That will allow the attached token to move within their parent(and update the offsets correctly) so when the parent moves afterwards it will keep the new position.
