### ISSUE TITLE
Foundry Server Debug Log shows warning...

### ISSUE THREAD

**Issue by karpana** [KayelGee/token-attacher#69]
When I restart my Foundry instance, this message is continually present in the `debug.log` file.

Foundry Version: v9 build 249
System: PF1
Host/Server Operating System: Raspberry Pi 4.

```
{"level":"warn","message":"Package token-attacher contains 1 compendium definitions that still use the deprecated 'entity' field instead of 'type'.","timestamp":"2022-02-07 09:18:05"}
```

**Comment by KayelGee** [comment]
Fixed in next update
