### ISSUE TITLE
The attachments are displaced after pasting

### ISSUE THREAD

**Issue by dungeonblaster** [KayelGee/token-attacher#7]
I am using grape_juice's isometric grid. Sometimes the selected token will copy and paste as intended, but others it will paste in the correct position, but the actor, walls, and drawings will be separated.
![image](https://user-images.githubusercontent.com/73514175/97257961-b4075700-17ed-11eb-8a1e-ea742baeada5.png)
As you can see on the right, the walls have been displaced by two grid spaces. The token has also been moved from the bottom-most floor square.
Original paste location: 
![image](https://user-images.githubusercontent.com/73514175/97257990-c97c8100-17ed-11eb-8d88-a2cdd604eca6.png)
Note that the textures are not tiles; they are drawings.

**Comment by KayelGee** [comment]
Can you reproduce the problem without the isometric module as I've no access to it?

**Comment by KayelGee** [comment]
Should be fixed in 3.1.1. If not then open a new issue.
