### ISSUE TITLE
setElementsMoveConstrainedStatus only works when set by GM

### ISSUE THREAD

**Issue by J-Dawe** [KayelGee/token-attacher#71]
When the GM runs setElementsMoveConstrainedStatus with canMoveConstrained set to true, the selected token can move inside its mount, as intended. However, if a player runs setElementsMoveConstrainedStatus with canMoveConstrained set to true, no one, not even the GM, can move the selected token. At first, you can try to move it, but it fails, and after a short time you can no longer attempt to move the token.

**Comment by KayelGee** [comment]
This also affects `setElementsLockStatus`

**Comment by KayelGee** [comment]
Fixed in next update
