### ISSUE TITLE
 Cannot read properties of undefined (reading 'hasOwnProperty')

### ISSUE THREAD

**Issue by drenghel** [KayelGee/token-attacher#72]
> Foundry version 9 build 255
> System: Starfinder: 0.18.2
> Modules active: 41
> Token Attacher: 4.4.3
> 

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'hasOwnProperty')
[Detected 1 package: token-attacher]
    at Function._attachElementsToToken (token-attacher.js:1076)
    at async Function.attachElementsToToken (token-attacher.js:1054)
_attachElementsToToken @ token-attacher.js:1076
async function (async)
attachElementsToToken @ token-attacher.js:1054
(anonymous) @ token-attacher.js:1143
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
```

Tittle is pretty self explanatory, whenever I try to use the module aka:
* Selecting a token
* Clicking on `Attach selected Element`
I get a toast with an message telling me to go to the console and I get said error.

I don't really have the time to try with a more minimal setup, but I'll try later if you guys have no idea why the error appears

Cheers

**Comment by KayelGee** [comment]
Just to be sure because that's a mistake poeple new to the module have done before, the correct steps to attach a token to another token are:

- Select a token
- Open the attach UI for that token
- Select another token
- Click attach in the attach ui
- Close attach ui

**Comment by KayelGee** [comment]
I could add some more info in the console when this happens.
Although I wonder why it threw an error in your case, as I was pretty sure I've caught them. I'll have to check this next time.
