### ISSUE TITLE
game.user._id has been changed to game.userId

### ISSUE THREAD

**Issue by ThirtyThreeAs** [KayelGee/token-attacher#75]
https://github.com/KayelGee/token-attacher/blob/c6400da582275d77ae04068ee7fcb06bf04f0991/packs/example-macros.db#L10

The example macro for creating a template and attaching it to a token uses game.user._id which was removed at some point in Foundry 9. The correct reference is now game.userId

**Comment by KayelGee** [comment]
it's funny how v9 is nearing it's end and these things still pop up
