### ISSUE TITLE
Token Attacher, Tagger, and Monk's Active Tiles issue

### ISSUE THREAD

**Issue by sblea88** [KayelGee/token-attacher#77]
The issue is a little strange to describe, I can record a video if need be.

Basically, using Tagger with Monk's Active Tiles (MAT) I have been setting up doors with two tiles and a third, "control" tile which targets the two primary tiles and toggles show/hide. What's happening is that when I set up the prefab with token attacher, I have the control tile targeting each tile using the following tagger reference: tile-something-{#}. This works for dragging the prefabs off of the actors screen, the tiles are appropriately numbered. However, the targeting for the show/hide toggle is emptied out rather than self-referencing the newly made tiles by their number.

What I've also discovered is that if I have Token Attacher active, if I try to set the targets for the show/hide toggle, it doesn't save. Even when I explicitly make sure I click "update tile" when I close it and reopen it, any changes I made selecting targets doesn't show up. I mention that it's a Token Attacher issue because disabling or deactivating the module allows me to then update the targets. Furthermore, I can then reenable Token Attacher and they all still have their targets and still work.

**Comment by KayelGee** [comment]
Yeah I'll definetly need a video of the issue because I can't replicate it on my end.
Also are you on the current version?
What system are you using?

**Comment by sblea88** [comment]
Having trouble reproducing it now. Not sure why, but I will update if need be. In the meantime, this might be case closed. Was current version. System was DnD5e.
