### ISSUE TITLE
Attached Light Source not moved with token

### ISSUE THREAD

**Issue by Gegh** [KayelGee/token-attacher#8]
Hi. I attached a Universal Lightsource to a NPC Token. When I move the token, the light source is not moved with the token. Or to be more precisly - from a Players View the Lightsource is not moved the need to move themselfs.

![grafik](https://user-images.githubusercontent.com/5196891/97716990-90c9f980-1ac4-11eb-8ea8-2e38dc0792e5.png)
Leah can see the Blip Token

![grafik](https://user-images.githubusercontent.com/5196891/97717141-c1119800-1ac4-11eb-9df4-9b3e123bb492.png)
GM moves token a bit down. Lightsource is NOT moved

![grafik](https://user-images.githubusercontent.com/5196891/97717240-db4b7600-1ac4-11eb-82f8-044026bb8297.png)
Player moves Leah one field down: Lightsource got refreshed

**Comment by Gegh** [comment]
I think I found the "solution" the Bliptoken has to have the "has vision" checkbox checked!

**Comment by KayelGee** [comment]
If I understand you correctly then this looks like a foundry core issue.
When a light source gets moved it doesn't update the vision of other tokens. The vision gets updated only if the token moves.
I've made a bug report to core foundry: https://discord.com/channels/170995199584108546/768568460816285696/771876417214349322

Should I have misunderstood your issue then please open a new issue.

**Comment by Gegh** [comment]
Thanks.
