### ISSUE TITLE
token height does not influence tile height

### ISSUE THREAD

**Issue by Orbdamu** [KayelGee/token-attacher#80]
While other things such as attached light switch height together with a token, tiles do not. that makes prefabs difficult to use in multilevel environments at different heights. Additionally, I wanted to start making 3d prefabs for 3d canvas, which is also just possible when token attacher behaves correctly in all 3 dimensions. I think in this case, other things might also need changing to allow for correct scaling of prefabs in 3 dimensions, but I'm not 100% sure about that.

**Comment by KayelGee** [comment]
Last time I checked it worked. Have you had a look at baileywikis stuff to see how to set it up correctly?

**Comment by Orbdamu** [comment]
I checked with the baileywiki discord, and it seemingly works on the initial placement, but any modification of the control tokens height after the initial placement is not applied to tiles.

**Comment by KayelGee** [comment]
I just realized this is about 3d canvas and not about levels right?

**Comment by Orbdamu** [comment]
It kinda is for my use case, but 3d canvas uses levels height (bottom) variable for tiles and has a dependency towards levels, Therefore I think fixing the issue for levels solves it in 3d canvas.

**Comment by Orbdamu** [comment]
Did you check for modifying the control tokens height after the initial placement? I am on the current version of token attacher 4.5.7 and the current version of levels 3.2.7, and for me the behavior is as follows: On initial placement, the tile height is correctly placed in relation to the control tokens height. If you change the control tokens height afterwards, any attached tiles remain on their placement height, while everything else that is attached and not a tile moves correctly in height wrt the control token.

**Comment by KayelGee** [comment]
can you make a video?

**Comment by Orbdamu** [comment]
Sure. here it is: 

https://user-images.githubusercontent.com/16311455/195164974-fe4e6450-c6bf-4dc5-ace0-e98aad7fdaa7.mp4

**Comment by KayelGee** [comment]
can you try setting top to something different than infinity and try again?

**Comment by Orbdamu** [comment]
now I am really confused. If I attach a tile to a new control token, it seems to work. If I use a control token that was created in a previous version, it won't work until I once detach the contents and reattach them and then assign the updated token as the prototype control token.

**Comment by KayelGee** [comment]
So the prefab was just broken then?

**Comment by Orbdamu** [comment]
I rather think any prefab that was created in an old version has that issue (atleast I tested a bunch of baileywiki prefabs and some own prefabs and they all acted that way). But I don't know if that is a fixable issue or the prefabs just need to be reattached

**Comment by KayelGee** [comment]
You can right click and export the actor and upload it here and I'll take a look if I see the cause.
If it's just one or a few prefabs you should contact baileywiki so they can fix them for their next releases.
