### ISSUE TITLE
Latest version cannot be installed

### ISSUE THREAD

**Issue by Mathias2803** [KayelGee/token-attacher#84]
The new version cannot be installed.

setup.js:292 Error: ENOENT: no such file or directory, open '/home/ubuntu/foundryuserdata/Data/modules/token-attacher.zip'
error @ setup.js:292
progress @ setup.js:326
(anonymous) @ setup.js:594
_onProgress @ setup.js:594
x.emit @ index.mjs:136
value @ socket.js:278
value @ socket.js:265
value @ socket.js:235
x.emit @ index.mjs:136
value @ manager.js:200
x.emit @ index.mjs:136
value @ index.js:119
value @ manager.js:192
x.emit @ index.mjs:136
value @ socket.js:323
x.emit @ index.mjs:136
value @ transport.js:104
value @ transport.js:97
ws.onmessage @ websocket.js:79
foundry.js:5058 Foundry VTT | Rendering ApplicationConfigurationForm
setup.js:292 Error: An unexpected error occurred when downloading file https://github.com/KayelGee/token-attacher/releases/download/v4.5.9/v4.5.9.zip: Not Found
    at fetchWithTimeout (file:///home/ubuntu/foundry/resources/app/common/utils/http.mjs:42:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async file:///home/ubuntu/foundry/resources/app/dist/files/downloader.mjs:1:616

**Comment by KayelGee** [comment]
Sorry I fucked up on the release naming. Should be fixed now
