### ISSUE TITLE
Template pasted twice after dragging a token with attached template from actors to canvas

### ISSUE THREAD

**Issue by DarKDinDoN** [KayelGee/token-attacher#9]
Hello,

FVTT 0.7.6
5e 0.99

When both the GM and the player controlling a token are connected and visualizing the same scene. If the GM place the controlled token on the canvas and the prototype token has a template attached
▶️ the attached template is created twice on the canvas for both GM and user view. This template can not be deleted. Refreshing the page shows the proper view (one template only)

![image](https://user-images.githubusercontent.com/1687854/98557360-633f3600-22a4-11eb-92ff-232b649a32a7.png)

**Comment by KayelGee** [comment]
I forgot to add a first gm check on the regeneration code. Thanks for the report.

**Comment by KayelGee** [comment]
Should be fixed in 3.1.1. If not open a new issue.
