### ISSUE TITLE
Rapid lag build up with prefabs

### ISSUE THREAD

**Issue by Psychotopia** [KayelGee/token-attacher#91]
2 or 3 prefabs is enough to lag one of my players solid when detached the lang ceases to be an issue think it might hav somthing to do with a version compatability isssue 
![image](https://user-images.githubusercontent.com/75271642/213608845-4cb8e881-f5c4-49c4-b092-9d828aea960f.png)

**Comment by KayelGee** [comment]
The version compatibility is just a general indicator that I haven't made any updates for the most recent version nothing more.
Can you look in the console of the player if it's spamming error messages maybe?
