### ISSUE TITLE
Issue: In 3D Canvas, tiles do not move vertically along with the actor they are attached to

### ISSUE THREAD

**Issue by JSwift777** [KayelGee/token-attacher#94]
Issue description: Upon either spawning a pre-existing prefab or creating a new one with token attacher, tiles will follow their linked actor horizontally but will only sometimes follow it vertically.

Steps to reproduce: For this test a blank new scene is created, 3D mode is enabled, a new actor is created and placed in the scene and then a selection of tiles are placed nearby (the token's icon has been changed to a wall with a gear to be more visible):

![image](https://user-images.githubusercontent.com/64264677/225449787-4d3c2fa0-180c-4003-a07f-0645fef52487.png)

The Token Attacher UI is then opened, the Select tool is enabled and then the tiles are selected in tile mode. 'Attach Selected Elements' is pressed and then the token attacher UI is closed.

![image](https://user-images.githubusercontent.com/64264677/225450747-ec16ab51-ee48-4d76-8be1-57db1bf32a57.png)

The token can now be moved around horizontally, copied and pasted, prototyped and then subsequently spawned in any scene, however if it is moved above or below altitude zero (move tokens vertically by clicking and holding on the token and then scrolling the mousewheel) the tiles do not follow.

![image](https://user-images.githubusercontent.com/64264677/225451020-1d883ad0-f1ab-4cb8-b1a6-7615a1a36c1d.png)

Muddying the waters somewhat, a prefab house like this one from the baileywiki module partially moves - having looked at the tiles involved, all the ones that do move have the "Block Sight" and "Block Movement" flags enabled, and all the ones that do not move have them disabled - however, the test tiles above also have "Block Sight" and "Block Movement" flags enabled so it seems like they are not directly the cause. I'm not even slightly a codemancer, so I'm not quite sure beyond that.

![image](https://user-images.githubusercontent.com/64264677/225453040-6378acff-e203-4283-84c7-f7405eaa2362.png)

If it's at all relevant, Lights do follow vertically as expected (the actual light fixtures just get left behind on the ground). Many thanks for your help with this.

**Comment by KayelGee** [comment]
Should be fixed
