### ISSUE TITLE
When I update Modules in v11

### ISSUE THREAD

**Issue by YenBenGrey** [KayelGee/token-attacher#98]
When I update modules in v11 it prompts me every time to change the filepath for Token Attacher, so I click OK.

Although it is green and says compatible with v11 it is still at 4.5.12.

The next time I update modules it prompts me again to go to the different filepath for 4.5.13. 

No idea if this is a problem or not in game.

**Comment by YenBenGrey** [comment]
<img width="399" alt="Screenshot 2023-06-08 at 17 58 31" src="https://github.com/KayelGee/token-attacher/assets/98095856/947f29bb-f7e9-4717-abbf-af685da8156a">
<img width="591" alt="Screenshot 2023-06-08 at 17 58 54" src="https://github.com/KayelGee/token-attacher/assets/98095856/75aec90c-9496-4146-87ac-9ae73ae6aebe">

**Comment by Doresain** [comment]
Same!

**Comment by thatlonelybugbear** [comment]
The 4.5.13 module.json points to the 4.5.12 version and zip.

Might need to adjust that

**Comment by KayelGee** [comment]
I think this should be fixed now, can you check?

**Comment by YenBenGrey** [comment]
<img width="599" alt="Screenshot 2023-06-09 at 18 08 55" src="https://github.com/KayelGee/token-attacher/assets/98095856/23094599-0fa9-412a-b64f-14a2a876bcd5">
