### ISSUE TITLE
4.5.13 can be downloaded by v10 despite incompatibility

### ISSUE THREAD

**Issue by GambetTV** [KayelGee/token-attacher#99]
Just so you know, I hit the Update All button, and even though it shouldn't be possible, your module updated despite not being compatible with v10. It then wouldn't show up for me in my module list, until I manually deleted it and downgraded.

**Comment by KayelGee** [comment]
Did you install the module manually via manifest or did you install it directly via foundrys module manager?

**Comment by KayelGee** [comment]
I meant originally.
I've checked the manifest from 4.5.13, but it looks alright. It has a minimum version of 11.
I've also checked the package in foundry and it also has a minimum version of 11.

I've had made a mistake at release #98 where the manifest pointed to the wrong version, maybe when you updated while this was wrong it might've caused this issue. But I don't know.
